import React from "react";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { WalletProvider } from "./providers/wallet-provider";
import { Navbar } from "@/components/navbar";
import { AsyncProvider } from "./providers/query-provider";
import { BarProviders } from "./providers/loader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AsyncProvider>
          <WalletProvider>
            <NuqsAdapter>
              <BarProviders>
                <Navbar />
                {children}
              </BarProviders>
            </NuqsAdapter>
          </WalletProvider>
        </AsyncProvider>
      </body>
    </html>
  );
}
